// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2NgW2g9f6Ryv53k41Gk9e01sAGKfdS08',
    appId: '1:435128982475:web:5326053a7dd40fc719744e',
    messagingSenderId: '435128982475',
    projectId: 'dhakker-160d0',
    authDomain: 'dhakker-160d0.firebaseapp.com',
    storageBucket: 'dhakker-160d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCga4QMm04PLNiIeKQf6aFbJfSnkXW_cEs',
    appId: '1:435128982475:android:b36a19b341e6c83b19744e',
    messagingSenderId: '435128982475',
    projectId: 'dhakker-160d0',
    storageBucket: 'dhakker-160d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCikupnAyxst2TiqDWKGCbB_4_6jf_86_Q',
    appId: '1:435128982475:ios:9bc343bccdaa842b19744e',
    messagingSenderId: '435128982475',
    projectId: 'dhakker-160d0',
    storageBucket: 'dhakker-160d0.firebasestorage.app',
    iosBundleId: 'com.example.dhakker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCikupnAyxst2TiqDWKGCbB_4_6jf_86_Q',
    appId: '1:435128982475:ios:9bc343bccdaa842b19744e',
    messagingSenderId: '435128982475',
    projectId: 'dhakker-160d0',
    storageBucket: 'dhakker-160d0.firebasestorage.app',
    iosBundleId: 'com.example.dhakker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2NgW2g9f6Ryv53k41Gk9e01sAGKfdS08',
    appId: '1:435128982475:web:e9e9feeacfd5859519744e',
    messagingSenderId: '435128982475',
    projectId: 'dhakker-160d0',
    authDomain: 'dhakker-160d0.firebaseapp.com',
    storageBucket: 'dhakker-160d0.firebasestorage.app',
  );
}
